name: ${project.name}
description: ${project.description}
author: AlbireoX
version: ${release.number}

main: net.celestiusmc.exosuit.ExoSuit

permissions:
  exosuit.suit:
    description: Exosuit usage.
    children:
      exosuit.helmet: true
      exosuit.chestplate: true
      exosuit.leggings: true
      exosuit.boots: true
  
  exosuit.helmet:
    description: Exosuit helmet.
    
  exosuit.chestplate:
    description: Exosuit chestplate.
    
  exosuit.leggings:
    description: Exosuit leggings.
    
  exosuit.boots:
    description: Exosuit boots.